#! /usr/bin/perl -wp
#
# kzify
#
# Kleines Skript um die "Kennzahl im Formular"-Vermerke automatisiert
# zu ergaenzen.  Die tooltips muessen bislang einzeilig sein.  Die
# Felder muessen dem Kz23 Schema entsprechend benannt sein ....
#

BEGIN {
  $curkz = 0;
}

if(m/\<widget .*id="Kz(\d{2})"/) { $curkz = $1;  }
if(m/\<\/widget/) { $curkz = 0; }

next unless $curkz;
next unless m/^(\s+)\<property name="tooltip"(.*)\>(.*)\<\/property\>/;

$_ = "$1<property name=\"tooltip\"$2>$3\n\nKennzahl im Formular: $curkz</property>\n";

