/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo mnu_file_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_NEW_ITEM (N_("_New"), NULL, on_file_new_activate, NULL),
  GNOMEUIINFO_MENU_OPEN_ITEM (on_file_open_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_ITEM (on_file_save_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_AS_ITEM (on_file_saveas_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_file_quit_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo mnu_edit_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_PREFERENCES_ITEM (on_edit_preferences_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo mnu_help_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_help_about_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (mnu_file_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (mnu_edit_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (mnu_help_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_taxbird (void)
{
  GtkWidget *taxbird;
  GtkWidget *dock;
  GtkWidget *toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolbar_new;
  GtkWidget *toolbar_open;
  GtkWidget *toolbar_save;
  GtkWidget *toolbar_separator;
  GtkWidget *toolbar_customize;
  GtkWidget *toolbar_execute;
  GtkWidget *hpane;
  GtkWidget *scroll_tv_sheets;
  GtkWidget *tv_sheets;
  GtkWidget *scroll_values;
  GtkWidget *viewport;
  GtkWidget *lblSpacer;
  GtkWidget *appbar;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  taxbird = gnome_app_new ("taxbird", _("taxbird"));
  gtk_window_set_default_size (GTK_WINDOW (taxbird), 540, 310);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (taxbird), TRUE);

  dock = GNOME_APP (taxbird)->dock;
  gtk_widget_show (dock);

  gnome_app_create_menus (GNOME_APP (taxbird), menubar_uiinfo);

  toolbar = gtk_toolbar_new ();
  gtk_widget_show (toolbar);
  gnome_app_add_toolbar (GNOME_APP (taxbird), GTK_TOOLBAR (toolbar), "toolbar",
                                BONOBO_DOCK_ITEM_BEH_EXCLUSIVE,
                                BONOBO_DOCK_TOP, 1, 0, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar));

  toolbar_new = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-new");
  gtk_widget_show (toolbar_new);
  gtk_container_add (GTK_CONTAINER (toolbar), toolbar_new);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_new), tooltips, _("Neue Datei"), NULL);

  toolbar_open = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-open");
  gtk_widget_show (toolbar_open);
  gtk_container_add (GTK_CONTAINER (toolbar), toolbar_open);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_open), tooltips, _("Datei öffnen"), NULL);

  toolbar_save = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-save");
  gtk_widget_show (toolbar_save);
  gtk_container_add (GTK_CONTAINER (toolbar), toolbar_save);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_save), tooltips, _("Datei speichern"), NULL);

  toolbar_separator = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (toolbar_separator);
  gtk_container_add (GTK_CONTAINER (toolbar), toolbar_separator);

  toolbar_customize = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-preferences");
  gtk_widget_show (toolbar_customize);
  gtk_container_add (GTK_CONTAINER (toolbar), toolbar_customize);

  toolbar_execute = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-execute");
  gtk_widget_show (toolbar_execute);
  gtk_container_add (GTK_CONTAINER (toolbar), toolbar_execute);

  hpane = gtk_hpaned_new ();
  gtk_widget_show (hpane);
  gnome_app_set_contents (GNOME_APP (taxbird), hpane);
  gtk_paned_set_position (GTK_PANED (hpane), 150);

  scroll_tv_sheets = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scroll_tv_sheets);
  gtk_paned_pack1 (GTK_PANED (hpane), scroll_tv_sheets, FALSE, TRUE);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scroll_tv_sheets), GTK_SHADOW_IN);

  tv_sheets = gtk_tree_view_new ();
  gtk_widget_show (tv_sheets);
  gtk_container_add (GTK_CONTAINER (scroll_tv_sheets), tv_sheets);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (tv_sheets), FALSE);

  scroll_values = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scroll_values);
  gtk_paned_pack2 (GTK_PANED (hpane), scroll_values, TRUE, TRUE);

  viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport);
  gtk_container_add (GTK_CONTAINER (scroll_values), viewport);

  lblSpacer = gtk_label_new ("");
  gtk_widget_show (lblSpacer);
  gtk_container_add (GTK_CONTAINER (viewport), lblSpacer);

  appbar = gnome_appbar_new (TRUE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_show (appbar);
  gnome_app_set_statusbar (GNOME_APP (taxbird), appbar);

  g_signal_connect ((gpointer) taxbird, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  gnome_app_install_menu_hints (GNOME_APP (taxbird), menubar_uiinfo);
  g_signal_connect ((gpointer) toolbar_new, "clicked",
                    G_CALLBACK (on_file_new_activate),
                    NULL);
  g_signal_connect ((gpointer) toolbar_open, "clicked",
                    G_CALLBACK (on_file_open_activate),
                    NULL);
  g_signal_connect ((gpointer) toolbar_save, "clicked",
                    G_CALLBACK (on_file_save_activate),
                    NULL);
  g_signal_connect ((gpointer) tv_sheets, "cursor_changed",
                    G_CALLBACK (on_tv_sheets_cursor_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (taxbird, taxbird, "taxbird");
  GLADE_HOOKUP_OBJECT (taxbird, dock, "dock");
  GLADE_HOOKUP_OBJECT (taxbird, menubar_uiinfo[0].widget, "mnu_file");
  GLADE_HOOKUP_OBJECT (taxbird, mnu_file_menu_uiinfo[0].widget, "mnu_file_new");
  GLADE_HOOKUP_OBJECT (taxbird, mnu_file_menu_uiinfo[1].widget, "mnu_file_open");
  GLADE_HOOKUP_OBJECT (taxbird, mnu_file_menu_uiinfo[2].widget, "mnu_file_save");
  GLADE_HOOKUP_OBJECT (taxbird, mnu_file_menu_uiinfo[3].widget, "mnu_file_saveas");
  GLADE_HOOKUP_OBJECT (taxbird, mnu_file_menu_uiinfo[4].widget, "mnu_file_separator");
  GLADE_HOOKUP_OBJECT (taxbird, mnu_file_menu_uiinfo[5].widget, "mnu_file_quit");
  GLADE_HOOKUP_OBJECT (taxbird, menubar_uiinfo[1].widget, "mnu_edit");
  GLADE_HOOKUP_OBJECT (taxbird, mnu_edit_menu_uiinfo[0].widget, "mnu_edit_preferences");
  GLADE_HOOKUP_OBJECT (taxbird, menubar_uiinfo[2].widget, "mnu_help");
  GLADE_HOOKUP_OBJECT (taxbird, mnu_help_menu_uiinfo[0].widget, "mnu_help_about");
  GLADE_HOOKUP_OBJECT (taxbird, toolbar, "toolbar");
  GLADE_HOOKUP_OBJECT (taxbird, toolbar_new, "toolbar_new");
  GLADE_HOOKUP_OBJECT (taxbird, toolbar_open, "toolbar_open");
  GLADE_HOOKUP_OBJECT (taxbird, toolbar_save, "toolbar_save");
  GLADE_HOOKUP_OBJECT (taxbird, toolbar_separator, "toolbar_separator");
  GLADE_HOOKUP_OBJECT (taxbird, toolbar_customize, "toolbar_customize");
  GLADE_HOOKUP_OBJECT (taxbird, toolbar_execute, "toolbar_execute");
  GLADE_HOOKUP_OBJECT (taxbird, hpane, "hpane");
  GLADE_HOOKUP_OBJECT (taxbird, scroll_tv_sheets, "scroll_tv_sheets");
  GLADE_HOOKUP_OBJECT (taxbird, tv_sheets, "tv_sheets");
  GLADE_HOOKUP_OBJECT (taxbird, scroll_values, "scroll_values");
  GLADE_HOOKUP_OBJECT (taxbird, viewport, "viewport");
  GLADE_HOOKUP_OBJECT (taxbird, lblSpacer, "lblSpacer");
  GLADE_HOOKUP_OBJECT (taxbird, appbar, "appbar");
  GLADE_HOOKUP_OBJECT_NO_REF (taxbird, tooltips, "tooltips");

  return taxbird;
}

GtkWidget*
create_dlgChooseTemplate (void)
{
  GtkWidget *dlgChooseTemplate;
  GtkWidget *vboxChooseTemplateDlg;
  GtkWidget *vboxTemplates;
  GtkWidget *lblTemplateDesc;
  GtkWidget *scrwTemplates;
  GtkWidget *lstTemplates;
  GtkWidget *dialog_action_area1;
  GtkWidget *cmdCancel;
  GtkWidget *cmdOK;

  dlgChooseTemplate = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dlgChooseTemplate), _("Choose Base Template"));
  gtk_window_set_modal (GTK_WINDOW (dlgChooseTemplate), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (dlgChooseTemplate), 480, 290);
  gtk_window_set_type_hint (GTK_WINDOW (dlgChooseTemplate), GDK_WINDOW_TYPE_HINT_DIALOG);

  vboxChooseTemplateDlg = GTK_DIALOG (dlgChooseTemplate)->vbox;
  gtk_widget_show (vboxChooseTemplateDlg);

  vboxTemplates = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxTemplates);
  gtk_box_pack_start (GTK_BOX (vboxChooseTemplateDlg), vboxTemplates, TRUE, TRUE, 0);

  lblTemplateDesc = gtk_label_new (_("Which template do you want to use as base for the new document?"));
  gtk_widget_show (lblTemplateDesc);
  gtk_box_pack_start (GTK_BOX (vboxTemplates), lblTemplateDesc, FALSE, TRUE, 15);
  gtk_label_set_justify (GTK_LABEL (lblTemplateDesc), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (lblTemplateDesc), TRUE);

  scrwTemplates = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrwTemplates);
  gtk_box_pack_start (GTK_BOX (vboxTemplates), scrwTemplates, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrwTemplates), GTK_SHADOW_IN);

  lstTemplates = gtk_tree_view_new ();
  gtk_widget_show (lstTemplates);
  gtk_container_add (GTK_CONTAINER (scrwTemplates), lstTemplates);

  dialog_action_area1 = GTK_DIALOG (dlgChooseTemplate)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cmdCancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cmdCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgChooseTemplate), cmdCancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cmdCancel, GTK_CAN_DEFAULT);

  cmdOK = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (cmdOK);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgChooseTemplate), cmdOK, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (cmdOK, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) cmdCancel, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dlgChooseTemplate));
  g_signal_connect ((gpointer) cmdOK, "clicked",
                    G_CALLBACK (on_choose_template_OK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlgChooseTemplate, dlgChooseTemplate, "dlgChooseTemplate");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgChooseTemplate, vboxChooseTemplateDlg, "vboxChooseTemplateDlg");
  GLADE_HOOKUP_OBJECT (dlgChooseTemplate, vboxTemplates, "vboxTemplates");
  GLADE_HOOKUP_OBJECT (dlgChooseTemplate, lblTemplateDesc, "lblTemplateDesc");
  GLADE_HOOKUP_OBJECT (dlgChooseTemplate, scrwTemplates, "scrwTemplates");
  GLADE_HOOKUP_OBJECT (dlgChooseTemplate, lstTemplates, "lstTemplates");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgChooseTemplate, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dlgChooseTemplate, cmdCancel, "cmdCancel");
  GLADE_HOOKUP_OBJECT (dlgChooseTemplate, cmdOK, "cmdOK");

  gtk_widget_grab_default (cmdOK);
  return dlgChooseTemplate;
}

GtkWidget*
create_dlgChooseFile (void)
{
  GtkWidget *dlgChooseFile;
  GtkWidget *vboxChooseFile;
  GtkWidget *dialog_action_area2;
  GtkWidget *cmdCancel;
  GtkWidget *cmdOK;

  dlgChooseFile = gtk_file_chooser_dialog_new (_("taxbird - Choose File"), NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_modal (GTK_WINDOW (dlgChooseFile), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dlgChooseFile), GDK_WINDOW_TYPE_HINT_DIALOG);

  vboxChooseFile = GTK_DIALOG (dlgChooseFile)->vbox;
  gtk_widget_show (vboxChooseFile);

  dialog_action_area2 = GTK_DIALOG (dlgChooseFile)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cmdCancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cmdCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgChooseFile), cmdCancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cmdCancel, GTK_CAN_DEFAULT);

  cmdOK = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (cmdOK);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgChooseFile), cmdOK, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (cmdOK, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) cmdCancel, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dlgChooseFile));
  g_signal_connect ((gpointer) cmdOK, "clicked",
                    G_CALLBACK (on_choose_file_OK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlgChooseFile, dlgChooseFile, "dlgChooseFile");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgChooseFile, vboxChooseFile, "vboxChooseFile");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgChooseFile, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dlgChooseFile, cmdCancel, "cmdCancel");
  GLADE_HOOKUP_OBJECT (dlgChooseFile, cmdOK, "cmdOK");

  gtk_widget_grab_default (cmdOK);
  return dlgChooseFile;
}

GtkWidget*
create_aboutTaxBird (void)
{
  const gchar *authors[] = {
    "Stefan Siegl <ssiegl@gmx.de>",
    NULL
  };
  const gchar *documenters[] = { NULL };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator_credits");
  GtkWidget *aboutTaxBird;

  if (!strcmp (translators, "translator_credits"))
    translators = NULL;
  aboutTaxBird = gnome_about_new ("taxbird", VERSION,
                        _("(C) 2004,05 Stefan Siegl"),
                        _("taxbird is a geier-based tax declarations capturing and transfer tool (for Germany) "),
                        authors,
                        documenters,
                        translators,
                        NULL);
  gtk_container_set_border_width (GTK_CONTAINER (aboutTaxBird), 5);
  gtk_window_set_type_hint (GTK_WINDOW (aboutTaxBird), GDK_WINDOW_TYPE_HINT_DIALOG);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutTaxBird, aboutTaxBird, "aboutTaxBird");

  return aboutTaxBird;
}

