/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_taxbird (void);
GtkWidget* create_dlgChooseTemplate (void);
GtkWidget* create_dlgChooseFile (void);
GtkWidget* create_aboutTaxBird (void);
